// Code generated by goyacc -o internal/parser/sqlite/ddl_gen.go -p sqlite internal/parser/sqlite/ddl.y. DO NOT EDIT.

//line internal/parser/sqlite/ddl.y:2
package sqlite

import __yyfmt__ "fmt"

//line internal/parser/sqlite/ddl.y:2

import "strings"

//line internal/parser/sqlite/ddl.y:7
type sqliteSymType struct {
	yys        int
	str        string
	strList    []string
	column     *columnDef
	elements   []tableElement
	element    tableElement
	constraint *constraintDef
	col        columnConstraint
	colcons    []columnConstraint
	boolVal    bool
	qname      qualifiedName
	fkTarget   fkTarget
	fkActions  fkActions
}

const CREATE_KW = 57346
const TABLE_KW = 57347
const TEMP_KW = 57348
const IF_KW = 57349
const NOT_KW = 57350
const EXISTS_KW = 57351
const PRIMARY_KW = 57352
const KEY_KW = 57353
const UNIQUE_KW = 57354
const CONSTRAINT_KW = 57355
const FOREIGN_KW = 57356
const REFERENCES_KW = 57357
const DEFAULT_KW = 57358
const AUTOINCREMENT_KW = 57359
const ON_KW = 57360
const DELETE_KW = 57361
const UPDATE_KW = 57362
const SET_KW = 57363
const CASCADE_KW = 57364
const RESTRICT_KW = 57365
const NO_KW = 57366
const ACTION_KW = 57367
const WITHOUT_KW = 57368
const ROWID_KW = 57369
const INDEX_KW = 57370
const TRUE_KW = 57371
const FALSE_KW = 57372
const NULL_KW = 57373
const CURRENT_TIMESTAMP_KW = 57374
const CURRENT_DATE_KW = 57375
const CURRENT_TIME_KW = 57376
const COLLATE_KW = 57377
const ASC_KW = 57378
const DESC_KW = 57379
const IDENT = 57380
const STRING = 57381
const NUMBER = 57382
const LPAREN = 57383
const RPAREN = 57384
const COMMA = 57385
const SEMICOLON = 57386
const DOT = 57387
const PLUS = 57388
const MINUS = 57389

var sqliteToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"CREATE_KW",
	"TABLE_KW",
	"TEMP_KW",
	"IF_KW",
	"NOT_KW",
	"EXISTS_KW",
	"PRIMARY_KW",
	"KEY_KW",
	"UNIQUE_KW",
	"CONSTRAINT_KW",
	"FOREIGN_KW",
	"REFERENCES_KW",
	"DEFAULT_KW",
	"AUTOINCREMENT_KW",
	"ON_KW",
	"DELETE_KW",
	"UPDATE_KW",
	"SET_KW",
	"CASCADE_KW",
	"RESTRICT_KW",
	"NO_KW",
	"ACTION_KW",
	"WITHOUT_KW",
	"ROWID_KW",
	"INDEX_KW",
	"TRUE_KW",
	"FALSE_KW",
	"NULL_KW",
	"CURRENT_TIMESTAMP_KW",
	"CURRENT_DATE_KW",
	"CURRENT_TIME_KW",
	"COLLATE_KW",
	"ASC_KW",
	"DESC_KW",
	"IDENT",
	"STRING",
	"NUMBER",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"SEMICOLON",
	"DOT",
	"PLUS",
	"MINUS",
}

var sqliteStatenames = [...]string{}

const sqliteEofCode = 1
const sqliteErrCode = 2
const sqliteInitialStackSize = 16

//line internal/parser/sqlite/ddl.y:291

//line yacctab:1
var sqliteExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 5,
	28, 74,
	-2, 6,
	-1, 37,
	42, 12,
	43, 12,
	-2, 54,
}

const sqlitePrivate = 57344

const sqliteLast = 157

var sqliteAct = [...]uint8{
	19, 136, 97, 110, 83, 59, 101, 24, 132, 121,
	89, 90, 88, 91, 92, 93, 123, 121, 22, 20,
	84, 85, 94, 7, 31, 34, 125, 95, 96, 122,
	121, 124, 39, 118, 43, 120, 121, 111, 31, 49,
	99, 100, 53, 77, 78, 60, 36, 37, 20, 76,
	73, 50, 72, 44, 23, 74, 75, 119, 116, 115,
	71, 54, 33, 20, 107, 108, 28, 80, 87, 81,
	144, 14, 61, 102, 102, 131, 98, 102, 55, 60,
	103, 109, 46, 104, 105, 143, 142, 20, 20, 134,
	135, 26, 18, 129, 82, 87, 112, 113, 63, 114,
	65, 25, 66, 35, 47, 68, 67, 69, 140, 137,
	138, 139, 40, 15, 41, 57, 42, 11, 51, 102,
	21, 64, 128, 12, 16, 127, 13, 5, 17, 6,
	106, 79, 133, 56, 8, 45, 4, 141, 3, 2,
	1, 130, 126, 117, 58, 86, 52, 32, 70, 38,
	30, 62, 48, 29, 27, 9, 10,
}

var sqlitePact = [...]int16{
	-1000, 123, -1000, -21, -21, 111, -1000, -1000, -1000, 121,
	43, -1000, -1000, 117, 117, 25, 112, 25, 13, -38,
	-1000, 92, 73, 49, 25, -1000, 25, 4, -1000, -1000,
	-1000, 25, 102, 25, -1000, 12, 56, 49, 10, -1000,
	107, 50, 104, -1000, 25, -1000, 45, -1000, 90, -1000,
	20, 11, 9, -1000, 25, 25, 8, -1000, 1, -1000,
	32, -1000, -1000, 38, -1000, 83, -1000, -19, 25, -1000,
	-2, -1000, 25, 25, -1000, -1000, 25, -1000, 25, 28,
	25, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -4, -4, -4, -19, 19, 18, -1000, -8, -1000,
	17, -7, -1000, -13, -26, -1000, -1000, -1000, -1000, -1000,
	-1000, -11, -1000, -1000, -16, -1000, -1000, -1000, 25, -1000,
	-1000, 25, -1000, 78, -1000, -1000, 57, -34, -1000, 25,
	-1000, 70, -1000, -1000, 87, 87, -1000, -1000, -1000, 61,
	54, -1000, -1000, -1000, -1000,
}

var sqlitePgo = [...]uint8{
	0, 113, 156, 155, 154, 66, 153, 152, 151, 150,
	0, 149, 148, 147, 146, 4, 145, 6, 144, 143,
	5, 76, 2, 142, 141, 1, 140, 139, 138, 129,
	136, 135, 133, 3, 131, 130,
}

var sqliteR1 = [...]int8{
	0, 26, 26, 27, 27, 28, 3, 3, 31, 31,
	4, 4, 4, 5, 5, 6, 11, 11, 11, 12,
	12, 7, 7, 8, 8, 8, 8, 8, 8, 8,
	9, 9, 9, 32, 32, 14, 14, 14, 14, 22,
	19, 19, 23, 23, 24, 24, 25, 25, 25, 25,
	25, 17, 17, 10, 13, 13, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 33, 33, 16,
	16, 21, 21, 30, 2, 2, 18, 18, 20, 34,
	34, 35, 35, 35, 1, 1, 29, 29,
}

var sqliteR2 = [...]int8{
	0, 0, 2, 2, 2, 9, 0, 1, 0, 2,
	1, 3, 2, 1, 1, 3, 1, 2, 4, 1,
	3, 0, 2, 2, 1, 2, 1, 2, 2, 1,
	6, 6, 8, 0, 1, 0, 1, 2, 2, 3,
	0, 3, 0, 2, 3, 3, 1, 1, 2, 2,
	2, 1, 3, 1, 0, 2, 1, 1, 1, 1,
	1, 1, 1, 2, 2, 2, 3, 0, 2, 2,
	2, 1, 3, 10, 0, 1, 1, 3, 3, 0,
	2, 0, 1, 1, 0, 3, 0, 1,
}

var sqliteChk = [...]int16{
	-1000, -26, -27, -28, -30, 4, -29, 44, -29, -3,
	-2, 6, 12, 5, 28, -1, 7, -1, -21, -10,
	38, 8, -10, 41, 45, 9, 18, -4, -5, -6,
	-9, -10, -13, 13, -10, -21, 42, 43, -11, -10,
	10, 12, 14, -10, 41, -31, 26, -5, -7, -10,
	41, 11, -14, -10, 11, 28, -32, 11, -18, -20,
	-10, 27, -8, 8, 31, 10, 12, 16, 15, 17,
	-12, 40, 41, 41, -10, -10, 41, 42, 43, -34,
	35, 31, 11, -15, 39, 40, -16, -10, 31, 29,
	30, 32, 33, 34, 41, 46, 47, -22, -21, 42,
	43, -17, -10, -17, -17, -20, -35, 36, 37, -10,
	-33, 41, -33, -33, -15, 40, 40, -19, 41, 40,
	42, 43, 42, 42, 42, 42, -23, -17, -10, 15,
	-24, 18, 42, -22, 19, 20, -25, 22, 23, 24,
	21, -25, 25, 31, 16,
}

var sqliteDef = [...]int8{
	1, -2, 2, 86, 86, -2, 3, 87, 4, 0,
	0, 7, 75, 84, 84, 0, 0, 0, 0, 71,
	53, 0, 0, 54, 0, 85, 0, 0, 10, 13,
	14, 0, 0, 0, 72, 0, 8, -2, 21, 16,
	0, 35, 33, 55, 0, 5, 0, 11, 15, 17,
	0, 0, 0, 36, 0, 0, 0, 34, 0, 76,
	79, 9, 22, 0, 24, 0, 26, 0, 0, 29,
	0, 19, 0, 0, 37, 38, 0, 73, 0, 81,
	0, 23, 25, 27, 56, 57, 58, 59, 60, 61,
	62, 67, 67, 67, 0, 0, 0, 28, 40, 18,
	0, 0, 51, 0, 0, 77, 78, 82, 83, 80,
	63, 0, 64, 65, 0, 69, 70, 42, 0, 20,
	30, 0, 31, 0, 68, 66, 39, 0, 52, 0,
	43, 0, 41, 32, 0, 0, 44, 46, 47, 0,
	0, 45, 48, 49, 50,
}

var sqliteTok1 = [...]int8{
	1,
}

var sqliteTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47,
}

var sqliteTok3 = [...]int8{
	0,
}

var sqliteErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	sqliteDebug        = 0
	sqliteErrorVerbose = false
)

type sqliteLexer interface {
	Lex(lval *sqliteSymType) int
	Error(s string)
}

type sqliteParser interface {
	Parse(sqliteLexer) int
	Lookahead() int
}

type sqliteParserImpl struct {
	lval  sqliteSymType
	stack [sqliteInitialStackSize]sqliteSymType
	char  int
}

func (p *sqliteParserImpl) Lookahead() int {
	return p.char
}

func sqliteNewParser() sqliteParser {
	return &sqliteParserImpl{}
}

const sqliteFlag = -1000

func sqliteTokname(c int) string {
	if c >= 1 && c-1 < len(sqliteToknames) {
		if sqliteToknames[c-1] != "" {
			return sqliteToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func sqliteStatname(s int) string {
	if s >= 0 && s < len(sqliteStatenames) {
		if sqliteStatenames[s] != "" {
			return sqliteStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func sqliteErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !sqliteErrorVerbose {
		return "syntax error"
	}

	for _, e := range sqliteErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + sqliteTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(sqlitePact[state])
	for tok := TOKSTART; tok-1 < len(sqliteToknames); tok++ {
		if n := base + tok; n >= 0 && n < sqliteLast && int(sqliteChk[int(sqliteAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if sqliteDef[state] == -2 {
		i := 0
		for sqliteExca[i] != -1 || int(sqliteExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; sqliteExca[i] >= 0; i += 2 {
			tok := int(sqliteExca[i])
			if tok < TOKSTART || sqliteExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if sqliteExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += sqliteTokname(tok)
	}
	return res
}

func sqlitelex1(lex sqliteLexer, lval *sqliteSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(sqliteTok1[0])
		goto out
	}
	if char < len(sqliteTok1) {
		token = int(sqliteTok1[char])
		goto out
	}
	if char >= sqlitePrivate {
		if char < sqlitePrivate+len(sqliteTok2) {
			token = int(sqliteTok2[char-sqlitePrivate])
			goto out
		}
	}
	for i := 0; i < len(sqliteTok3); i += 2 {
		token = int(sqliteTok3[i+0])
		if token == char {
			token = int(sqliteTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(sqliteTok2[1]) /* unknown char */
	}
	if sqliteDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", sqliteTokname(token), uint(char))
	}
	return char, token
}

func sqliteParse(sqlitelex sqliteLexer) int {
	return sqliteNewParser().Parse(sqlitelex)
}

func (sqlitercvr *sqliteParserImpl) Parse(sqlitelex sqliteLexer) int {
	var sqliten int
	var sqliteVAL sqliteSymType
	var sqliteDollar []sqliteSymType
	_ = sqliteDollar // silence set and not used
	sqliteS := sqlitercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	sqlitestate := 0
	sqlitercvr.char = -1
	sqlitetoken := -1 // sqlitercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		sqlitestate = -1
		sqlitercvr.char = -1
		sqlitetoken = -1
	}()
	sqlitep := -1
	goto sqlitestack

ret0:
	return 0

ret1:
	return 1

sqlitestack:
	/* put a state and value onto the stack */
	if sqliteDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", sqliteTokname(sqlitetoken), sqliteStatname(sqlitestate))
	}

	sqlitep++
	if sqlitep >= len(sqliteS) {
		nyys := make([]sqliteSymType, len(sqliteS)*2)
		copy(nyys, sqliteS)
		sqliteS = nyys
	}
	sqliteS[sqlitep] = sqliteVAL
	sqliteS[sqlitep].yys = sqlitestate

sqlitenewstate:
	sqliten = int(sqlitePact[sqlitestate])
	if sqliten <= sqliteFlag {
		goto sqlitedefault /* simple state */
	}
	if sqlitercvr.char < 0 {
		sqlitercvr.char, sqlitetoken = sqlitelex1(sqlitelex, &sqlitercvr.lval)
	}
	sqliten += sqlitetoken
	if sqliten < 0 || sqliten >= sqliteLast {
		goto sqlitedefault
	}
	sqliten = int(sqliteAct[sqliten])
	if int(sqliteChk[sqliten]) == sqlitetoken { /* valid shift */
		sqlitercvr.char = -1
		sqlitetoken = -1
		sqliteVAL = sqlitercvr.lval
		sqlitestate = sqliten
		if Errflag > 0 {
			Errflag--
		}
		goto sqlitestack
	}

sqlitedefault:
	/* default state action */
	sqliten = int(sqliteDef[sqlitestate])
	if sqliten == -2 {
		if sqlitercvr.char < 0 {
			sqlitercvr.char, sqlitetoken = sqlitelex1(sqlitelex, &sqlitercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if sqliteExca[xi+0] == -1 && int(sqliteExca[xi+1]) == sqlitestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			sqliten = int(sqliteExca[xi+0])
			if sqliten < 0 || sqliten == sqlitetoken {
				break
			}
		}
		sqliten = int(sqliteExca[xi+1])
		if sqliten < 0 {
			goto ret0
		}
	}
	if sqliten == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			sqlitelex.Error(sqliteErrorMessage(sqlitestate, sqlitetoken))
			Nerrs++
			if sqliteDebug >= 1 {
				__yyfmt__.Printf("%s", sqliteStatname(sqlitestate))
				__yyfmt__.Printf(" saw %s\n", sqliteTokname(sqlitetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for sqlitep >= 0 {
				sqliten = int(sqlitePact[sqliteS[sqlitep].yys]) + sqliteErrCode
				if sqliten >= 0 && sqliten < sqliteLast {
					sqlitestate = int(sqliteAct[sqliten]) /* simulate a shift of "error" */
					if int(sqliteChk[sqlitestate]) == sqliteErrCode {
						goto sqlitestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if sqliteDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", sqliteS[sqlitep].yys)
				}
				sqlitep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if sqliteDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", sqliteTokname(sqlitetoken))
			}
			if sqlitetoken == sqliteEofCode {
				goto ret1
			}
			sqlitercvr.char = -1
			sqlitetoken = -1
			goto sqlitenewstate /* try again in the same state */
		}
	}

	/* reduction by production sqliten */
	if sqliteDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", sqliten, sqliteStatname(sqlitestate))
	}

	sqlitent := sqliten
	sqlitept := sqlitep
	_ = sqlitept // guard against "declared and not used"

	sqlitep -= int(sqliteR2[sqliten])
	// sqlitep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if sqlitep+1 >= len(sqliteS) {
		nyys := make([]sqliteSymType, len(sqliteS)*2)
		copy(nyys, sqliteS)
		sqliteS = nyys
	}
	sqliteVAL = sqliteS[sqlitep+1]

	/* consult goto table to find next state */
	sqliten = int(sqliteR1[sqliten])
	sqliteg := int(sqlitePgo[sqliten])
	sqlitej := sqliteg + sqliteS[sqlitep].yys + 1

	if sqlitej >= sqliteLast {
		sqlitestate = int(sqliteAct[sqliteg])
	} else {
		sqlitestate = int(sqliteAct[sqlitej])
		if int(sqliteChk[sqlitestate]) != -sqliten {
			sqlitestate = int(sqliteAct[sqliteg])
		}
	}
	// dummy call; replaced with literal code
	switch sqlitent {

	case 5:
		sqliteDollar = sqliteS[sqlitept-9 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:54
		{
			lex := sqlitelex.(*lexer)
			tb := newTableBuilder(sqliteDollar[5].qname.schema, sqliteDollar[5].qname.name)
			for _, elem := range sqliteDollar[7].elements {
				if elem.column != nil {
					tb.addColumn(elem.column)
				}
				if elem.constraint != nil {
					tb.applyConstraint(elem.constraint)
				}
			}
			lex.addTable(tb)
		}
	case 6:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:70
		{
			sqliteVAL.boolVal = false
		}
	case 7:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:71
		{
			sqliteVAL.boolVal = true
		}
	case 10:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:80
		{
			sqliteVAL.elements = []tableElement{sqliteDollar[1].element}
		}
	case 11:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:81
		{
			sqliteVAL.elements = append(sqliteDollar[1].elements, sqliteDollar[3].element)
		}
	case 12:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:82
		{
			sqliteVAL.elements = sqliteDollar[1].elements
		}
	case 13:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:86
		{
			sqliteVAL.element = tableElement{column: sqliteDollar[1].column}
		}
	case 14:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:87
		{
			sqliteVAL.element = tableElement{constraint: sqliteDollar[1].constraint}
		}
	case 15:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:91
		{
			col := &columnDef{name: sqliteDollar[1].str, dbType: sqliteDollar[2].str}
			applyColumnConstraints(col, sqliteDollar[3].colcons)
			sqliteVAL.column = col
		}
	case 16:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:99
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 17:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:100
		{
			sqliteVAL.str = sqliteDollar[1].str + " " + sqliteDollar[2].str
		}
	case 18:
		sqliteDollar = sqliteS[sqlitept-4 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:101
		{
			sqliteVAL.str = sqliteDollar[1].str + "(" + sqliteDollar[3].str + ")"
		}
	case 19:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:105
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 20:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:106
		{
			sqliteVAL.str = sqliteDollar[1].str + "," + sqliteDollar[3].str
		}
	case 21:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:110
		{
			sqliteVAL.colcons = nil
		}
	case 22:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:111
		{
			sqliteVAL.colcons = append(sqliteDollar[1].colcons, sqliteDollar[2].col)
		}
	case 23:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:115
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintNotNull}
		}
	case 24:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:116
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintNull}
		}
	case 25:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:117
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintPrimaryKey}
		}
	case 26:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:118
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintUnique}
		}
	case 27:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:119
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintDefault, value: sqliteDollar[2].str}
		}
	case 28:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:120
		{
			ref := sqliteDollar[2].fkTarget
			sqliteVAL.col = columnConstraint{kind: columnConstraintForeignKey, fk: &ref}
		}
	case 29:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:124
		{
			sqliteVAL.col = columnConstraint{kind: columnConstraintPrimaryKey}
		}
	case 30:
		sqliteDollar = sqliteS[sqlitept-6 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:128
		{
			sqliteVAL.constraint = &constraintDef{kind: constraintPrimaryKey, name: sqliteDollar[1].str, columns: sqliteDollar[5].strList}
		}
	case 31:
		sqliteDollar = sqliteS[sqlitept-6 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:131
		{
			name := sqliteDollar[1].str
			if name == "" {
				name = sqliteDollar[3].str
			}
			sqliteVAL.constraint = &constraintDef{kind: constraintUnique, name: name, columns: sqliteDollar[5].strList}
		}
	case 32:
		sqliteDollar = sqliteS[sqlitept-8 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:138
		{
			sqliteVAL.constraint = &constraintDef{
				kind:    constraintForeignKey,
				name:    sqliteDollar[1].str,
				columns: sqliteDollar[5].strList,
				fk:      sqliteDollar[8].fkTarget,
			}
		}
	case 35:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:154
		{
			sqliteVAL.str = ""
		}
	case 36:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:155
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 37:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:156
		{
			sqliteVAL.str = sqliteDollar[2].str
		}
	case 38:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:157
		{
			sqliteVAL.str = sqliteDollar[2].str
		}
	case 39:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:161
		{
			sqliteVAL.fkTarget = fkTarget{
				table:   sqliteDollar[1].qname,
				columns: sqliteDollar[2].strList,
				actions: sqliteDollar[3].fkActions,
			}
		}
	case 40:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:171
		{
			sqliteVAL.strList = nil
		}
	case 41:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:172
		{
			sqliteVAL.strList = sqliteDollar[2].strList
		}
	case 42:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:176
		{
			sqliteVAL.fkActions = fkActions{}
		}
	case 43:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:177
		{
			sqliteVAL.fkActions = sqliteDollar[1].fkActions
			if sqliteDollar[2].fkActions.onDelete != "" {
				sqliteVAL.fkActions.onDelete = sqliteDollar[2].fkActions.onDelete
			}
			if sqliteDollar[2].fkActions.onUpdate != "" {
				sqliteVAL.fkActions.onUpdate = sqliteDollar[2].fkActions.onUpdate
			}
		}
	case 44:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:189
		{
			sqliteVAL.fkActions = fkActions{onDelete: sqliteDollar[3].str}
		}
	case 45:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:190
		{
			sqliteVAL.fkActions = fkActions{onUpdate: sqliteDollar[3].str}
		}
	case 46:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:194
		{
			sqliteVAL.str = "CASCADE"
		}
	case 47:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:195
		{
			sqliteVAL.str = "RESTRICT"
		}
	case 48:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:196
		{
			sqliteVAL.str = "NO ACTION"
		}
	case 49:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:197
		{
			sqliteVAL.str = "SET NULL"
		}
	case 50:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:198
		{
			sqliteVAL.str = "SET DEFAULT"
		}
	case 51:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:202
		{
			sqliteVAL.strList = []string{sqliteDollar[1].str}
		}
	case 52:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:203
		{
			sqliteVAL.strList = append(sqliteDollar[1].strList, sqliteDollar[3].str)
		}
	case 53:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:207
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 54:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:211
		{
			sqliteVAL.str = ""
		}
	case 55:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:212
		{
			sqliteVAL.str = sqliteDollar[2].str
		}
	case 56:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:216
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 57:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:217
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 58:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:218
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 59:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:219
		{
			sqliteVAL.str = strings.ToUpper(sqliteDollar[1].str)
		}
	case 60:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:220
		{
			sqliteVAL.str = "NULL"
		}
	case 61:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:221
		{
			sqliteVAL.str = "TRUE"
		}
	case 62:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:222
		{
			sqliteVAL.str = "FALSE"
		}
	case 63:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:223
		{
			sqliteVAL.str = "CURRENT_TIMESTAMP"
		}
	case 64:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:224
		{
			sqliteVAL.str = "CURRENT_DATE"
		}
	case 65:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:225
		{
			sqliteVAL.str = "CURRENT_TIME"
		}
	case 66:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:226
		{
			sqliteVAL.str = sqliteDollar[2].str
		}
	case 69:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:235
		{
			sqliteVAL.str = "+" + sqliteDollar[2].str
		}
	case 70:
		sqliteDollar = sqliteS[sqlitept-2 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:236
		{
			sqliteVAL.str = "-" + sqliteDollar[2].str
		}
	case 71:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:240
		{
			sqliteVAL.qname = qualifiedName{name: sqliteDollar[1].str}
		}
	case 72:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:241
		{
			sqliteVAL.qname = qualifiedName{schema: sqliteDollar[1].str, name: sqliteDollar[3].str}
		}
	case 73:
		sqliteDollar = sqliteS[sqlitept-10 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:245
		{
			lex := sqlitelex.(*lexer)
			lex.addIndex(indexDef{
				schema:  sqliteDollar[7].qname.schema,
				table:   sqliteDollar[7].qname.name,
				name:    sqliteDollar[5].str,
				columns: sqliteDollar[9].strList,
				unique:  sqliteDollar[2].boolVal,
			})
		}
	case 74:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:258
		{
			sqliteVAL.boolVal = false
		}
	case 75:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:259
		{
			sqliteVAL.boolVal = true
		}
	case 76:
		sqliteDollar = sqliteS[sqlitept-1 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:263
		{
			sqliteVAL.strList = []string{sqliteDollar[1].str}
		}
	case 77:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:264
		{
			sqliteVAL.strList = append(sqliteDollar[1].strList, sqliteDollar[3].str)
		}
	case 78:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:268
		{
			sqliteVAL.str = sqliteDollar[1].str
		}
	case 84:
		sqliteDollar = sqliteS[sqlitept-0 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:283
		{
			sqliteVAL.boolVal = false
		}
	case 85:
		sqliteDollar = sqliteS[sqlitept-3 : sqlitept+1]
//line internal/parser/sqlite/ddl.y:284
		{
			sqliteVAL.boolVal = true
		}
	}
	goto sqlitestack /* stack new state and value */
}
