// Code generated by goyacc -o ddl_gen.go -p postgres ddl.y. DO NOT EDIT.

//line ddl.y:2
package postgres

import __yyfmt__ "fmt"

//line ddl.y:2

import "strings"

//line ddl.y:7
type postgresSymType struct {
	yys        int
	str        string
	strList    []string
	column     *columnDef
	elements   []tableElement
	element    tableElement
	constraint *constraintDef
	col        columnConstraint
	colcons    []columnConstraint
	boolVal    bool
	qname      qualifiedName
	fkTarget   fkTarget
	fkActions  fkActions
}

const CREATE_KW = 57346
const TABLE_KW = 57347
const INDEX_KW = 57348
const IF_KW = 57349
const NOT_KW = 57350
const EXISTS_KW = 57351
const PRIMARY_KW = 57352
const KEY_KW = 57353
const UNIQUE_KW = 57354
const CONSTRAINT_KW = 57355
const FOREIGN_KW = 57356
const REFERENCES_KW = 57357
const DEFAULT_KW = 57358
const ON_KW = 57359
const DELETE_KW = 57360
const UPDATE_KW = 57361
const SET_KW = 57362
const CASCADE_KW = 57363
const RESTRICT_KW = 57364
const NO_KW = 57365
const ACTION_KW = 57366
const NULL_KW = 57367
const TRUE_KW = 57368
const FALSE_KW = 57369
const CURRENT_TIMESTAMP_KW = 57370
const CURRENT_DATE_KW = 57371
const CURRENT_TIME_KW = 57372
const ALTER_KW = 57373
const ADD_KW = 57374
const COLUMN_KW = 57375
const DROP_KW = 57376
const ONLY_KW = 57377
const TABLESPACE_KW = 57378
const WITH_KW = 57379
const CHECK_KW = 57380
const MATCH_KW = 57381
const DEFERRABLE_KW = 57382
const INITIALLY_KW = 57383
const DEFERRED_KW = 57384
const IMMEDIATE_KW = 57385
const GENERATED_KW = 57386
const ALWAYS_KW = 57387
const BY_KW = 57388
const AS_KW = 57389
const IDENTITY_KW = 57390
const USING_KW = 57391
const INCLUDE_KW = 57392
const COMMENT_KW = 57393
const IS_KW = 57394
const COLLATE_KW = 57395
const IDENT = 57396
const STRING = 57397
const NUMBER = 57398
const LPAREN = 57399
const RPAREN = 57400
const COMMA = 57401
const SEMICOLON = 57402
const DOT = 57403
const PLUS = 57404
const MINUS = 57405
const STAR = 57406
const SLASH = 57407
const TYPECAST = 57408
const LBRACKET = 57409
const RBRACKET = 57410
const EQUALS = 57411
const UMINUS = 57412
const UPLUS = 57413

var postgresToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"CREATE_KW",
	"TABLE_KW",
	"INDEX_KW",
	"IF_KW",
	"NOT_KW",
	"EXISTS_KW",
	"PRIMARY_KW",
	"KEY_KW",
	"UNIQUE_KW",
	"CONSTRAINT_KW",
	"FOREIGN_KW",
	"REFERENCES_KW",
	"DEFAULT_KW",
	"ON_KW",
	"DELETE_KW",
	"UPDATE_KW",
	"SET_KW",
	"CASCADE_KW",
	"RESTRICT_KW",
	"NO_KW",
	"ACTION_KW",
	"NULL_KW",
	"TRUE_KW",
	"FALSE_KW",
	"CURRENT_TIMESTAMP_KW",
	"CURRENT_DATE_KW",
	"CURRENT_TIME_KW",
	"ALTER_KW",
	"ADD_KW",
	"COLUMN_KW",
	"DROP_KW",
	"ONLY_KW",
	"TABLESPACE_KW",
	"WITH_KW",
	"CHECK_KW",
	"MATCH_KW",
	"DEFERRABLE_KW",
	"INITIALLY_KW",
	"DEFERRED_KW",
	"IMMEDIATE_KW",
	"GENERATED_KW",
	"ALWAYS_KW",
	"BY_KW",
	"AS_KW",
	"IDENTITY_KW",
	"USING_KW",
	"INCLUDE_KW",
	"COMMENT_KW",
	"IS_KW",
	"COLLATE_KW",
	"IDENT",
	"STRING",
	"NUMBER",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"SEMICOLON",
	"DOT",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"TYPECAST",
	"LBRACKET",
	"RBRACKET",
	"EQUALS",
	"UMINUS",
	"UPLUS",
}

var postgresStatenames = [...]string{}

const postgresEofCode = 1
const postgresErrCode = 2
const postgresInitialStackSize = 16

//line ddl.y:360

func quoteLiteral(in string) string {
	if strings.HasPrefix(in, "'") {
		return in
	}
	return "'" + strings.ReplaceAll(in, "'", "''") + "'"
}

//line yacctab:1
var postgresExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 5,
	6, 107,
	-2, 6,
	-1, 38,
	58, 21,
	59, 21,
	-2, 53,
}

const postgresPrivate = 57344

const postgresLast = 242

var postgresAct = [...]uint8{
	173, 106, 162, 192, 136, 84, 107, 91, 48, 87,
	19, 125, 79, 126, 93, 61, 17, 20, 127, 128,
	129, 130, 126, 132, 131, 32, 35, 131, 20, 18,
	24, 7, 54, 172, 40, 171, 45, 36, 191, 121,
	32, 53, 55, 170, 58, 129, 130, 126, 165, 64,
	161, 62, 66, 82, 127, 128, 129, 130, 126, 189,
	121, 144, 121, 143, 121, 85, 81, 88, 80, 102,
	100, 101, 103, 104, 105, 142, 121, 110, 123, 124,
	122, 121, 85, 85, 85, 65, 116, 117, 118, 63,
	109, 120, 114, 115, 37, 38, 23, 141, 18, 98,
	99, 95, 119, 133, 134, 135, 97, 96, 78, 18,
	20, 147, 34, 102, 100, 101, 103, 104, 105, 138,
	18, 151, 150, 145, 12, 47, 88, 149, 180, 166,
	167, 139, 184, 157, 148, 153, 154, 155, 156, 163,
	160, 152, 18, 98, 99, 95, 112, 113, 186, 185,
	97, 96, 68, 18, 70, 169, 71, 137, 27, 73,
	72, 41, 199, 42, 29, 43, 11, 85, 176, 69,
	201, 179, 85, 50, 49, 181, 182, 178, 89, 200,
	183, 22, 74, 187, 188, 108, 190, 140, 76, 44,
	168, 90, 197, 198, 60, 25, 56, 75, 21, 202,
	175, 177, 16, 51, 196, 193, 194, 195, 26, 14,
	13, 6, 5, 146, 46, 59, 8, 83, 111, 86,
	9, 4, 3, 2, 1, 174, 164, 159, 158, 94,
	92, 57, 33, 77, 39, 31, 67, 52, 30, 28,
	10, 15,
}

var postgresPact = [...]int16{
	-1000, 208, -1000, -29, -29, 112, -1000, -1000, -1000, 205,
	203, -1000, -1000, 195, 55, 55, 190, 164, -1000, 39,
	-31, 186, 123, 99, 55, -1000, 55, -1000, 36, -1000,
	-1000, -1000, 55, 151, 55, -1000, 76, 137, 99, -25,
	-1000, 185, 55, 183, -6, -1000, 32, 55, -1000, 28,
	55, -1000, 144, -1000, 52, -56, 11, 9, -1000, -4,
	-1000, -1000, -1000, 55, -1000, 55, -1000, -1000, 153, -1000,
	180, -1000, 88, 123, -6, 55, 101, 34, -1000, -1000,
	55, 55, 55, 44, 22, -1000, 20, -1000, -58, -1000,
	-1000, -44, -1000, -34, -1000, 88, 88, 88, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 118, 55, -1000,
	-1000, -1000, 84, 171, -1000, 41, 17, 5, 3, -1000,
	-44, 55, 61, -1000, 55, 66, 55, 88, 88, 88,
	88, 55, 88, -8, -53, -53, -1000, 55, -9, 81,
	83, -1000, -1000, -1000, 175, -1000, 137, -14, -1000, -1000,
	-1000, -1000, -37, -19, -19, -53, -53, -1000, -23, -26,
	-44, -1000, 160, -1000, -1000, 55, -1000, 80, 123, -1000,
	55, -1000, 88, -1000, -1000, -1000, 92, 106, 165, 1,
	-1000, 118, -20, -44, -1000, -1000, -1000, 184, 184, -1000,
	-1000, -1000, -1000, -1000, -1000, 138, 154, -1000, 160, -1000,
	-1000, -1000, -1000,
}

var postgresPgo = [...]uint8{
	0, 241, 240, 185, 239, 164, 238, 237, 236, 235,
	1, 234, 233, 232, 231, 7, 230, 229, 14, 8,
	228, 227, 4, 5, 226, 10, 6, 2, 225, 3,
	224, 223, 222, 211, 221, 220, 219, 9, 0, 15,
	218, 217, 215, 214, 213,
}

var postgresR1 = [...]int8{
	0, 30, 30, 31, 31, 32, 35, 35, 19, 19,
	19, 36, 36, 37, 37, 37, 37, 1, 1, 4,
	4, 4, 5, 5, 6, 11, 11, 11, 11, 12,
	12, 7, 7, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 40, 40, 39, 41, 41, 9, 9, 9,
	9, 42, 42, 13, 13, 14, 14, 26, 22, 22,
	24, 24, 27, 27, 28, 28, 29, 29, 29, 29,
	29, 38, 38, 38, 38, 38, 23, 23, 25, 25,
	18, 18, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
	16, 17, 20, 20, 21, 21, 34, 2, 2, 43,
	43, 44, 44, 33, 33, 10, 3, 3,
}

var postgresR2 = [...]int8{
	0, 0, 2, 2, 2, 9, 0, 1, 0, 4,
	2, 1, 3, 1, 3, 3, 3, 0, 3, 1,
	3, 2, 1, 1, 3, 1, 2, 4, 3, 1,
	3, 0, 2, 2, 1, 2, 1, 2, 5, 2,
	2, 2, 3, 4, 3, 0, 2, 6, 6, 11,
	3, 0, 1, 0, 2, 0, 1, 3, 0, 2,
	0, 3, 0, 2, 3, 3, 1, 1, 2, 2,
	2, 0, 1, 2, 2, 2, 1, 3, 1, 3,
	1, 3, 1, 1, 1, 3, 3, 3, 3, 3,
	3, 2, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 4, 0, 1, 1, 3, 13, 0, 1, 0,
	2, 0, 4, 0, 1, 1, 0, 1,
}

var postgresChk = [...]int16{
	-1000, -30, -31, -32, -34, 4, -33, 60, -33, -35,
	-2, 54, 12, 5, 6, -1, 7, -10, 54, -25,
	-10, 8, 17, 57, 61, 9, -3, 35, -4, -5,
	-6, -9, -10, -13, 13, -10, -25, 58, 59, -11,
	-10, 10, 12, 14, 38, -10, -43, 49, -19, 37,
	36, -5, -7, -10, 57, 67, 11, -14, -10, -42,
	11, -39, 57, 57, -10, 57, -10, -8, 8, 25,
	10, 12, 16, 15, 38, 53, 44, -12, 56, 68,
	57, 57, 57, -41, -23, -10, -36, -37, -10, 25,
	11, -15, -16, -18, -17, 57, 63, 62, 55, 56,
	26, 27, 25, 28, 29, 30, -10, -26, -3, -39,
	-10, -40, 45, 46, 58, 59, -23, -23, -23, 58,
	-15, 59, 58, 58, 59, 69, 66, 62, 63, 64,
	65, 61, 57, -15, -15, -15, -22, 39, -25, 47,
	16, 56, 58, 58, 58, -10, -44, 50, -37, -10,
	56, 55, -18, -15, -15, -15, -15, -10, -20, -21,
	-15, 58, -27, -10, -24, 57, 48, 47, 15, -19,
	57, 58, 59, -38, -28, 40, 8, 41, 17, -23,
	48, -26, -23, -15, 40, 43, 42, 18, 19, 58,
	-22, 58, -29, 21, 22, 23, 20, -29, -27, 24,
	25, 16, -38,
}

var postgresDef = [...]int8{
	1, -2, 2, 113, 113, -2, 3, 114, 4, 0,
	0, 7, 108, 17, 0, 0, 0, 0, 115, 0,
	78, 0, 116, 53, 0, 18, 0, 117, 0, 19,
	22, 23, 0, 0, 0, 79, 109, 8, -2, 31,
	25, 0, 55, 51, 0, 54, 0, 0, 5, 0,
	0, 20, 24, 26, 0, 0, 0, 0, 56, 0,
	52, 50, 45, 0, 110, 0, 10, 32, 0, 34,
	0, 36, 0, 116, 0, 0, 0, 0, 29, 28,
	0, 0, 0, 0, 0, 76, 0, 11, 13, 33,
	35, 37, 82, 83, 84, 0, 0, 0, 93, 94,
	95, 96, 97, 98, 99, 100, 80, 58, 0, 39,
	40, 41, 0, 0, 27, 0, 0, 0, 0, 44,
	46, 0, 111, 9, 0, 0, 0, 0, 0, 0,
	0, 0, 102, 0, 91, 92, 62, 0, 60, 0,
	0, 30, 47, 48, 0, 77, 8, 0, 12, 14,
	15, 16, 86, 87, 88, 89, 90, 81, 0, 103,
	104, 85, 71, 59, 57, 0, 42, 0, 116, 106,
	0, 101, 0, 38, 63, 72, 0, 0, 0, 0,
	43, 58, 0, 105, 73, 74, 75, 0, 0, 61,
	62, 112, 64, 66, 67, 0, 0, 65, 71, 68,
	69, 70, 49,
}

var postgresTok1 = [...]int8{
	1,
}

var postgresTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
}

var postgresTok3 = [...]int8{
	0,
}

var postgresErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	postgresDebug        = 0
	postgresErrorVerbose = false
)

type postgresLexer interface {
	Lex(lval *postgresSymType) int
	Error(s string)
}

type postgresParser interface {
	Parse(postgresLexer) int
	Lookahead() int
}

type postgresParserImpl struct {
	lval  postgresSymType
	stack [postgresInitialStackSize]postgresSymType
	char  int
}

func (p *postgresParserImpl) Lookahead() int {
	return p.char
}

func postgresNewParser() postgresParser {
	return &postgresParserImpl{}
}

const postgresFlag = -1000

func postgresTokname(c int) string {
	if c >= 1 && c-1 < len(postgresToknames) {
		if postgresToknames[c-1] != "" {
			return postgresToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func postgresStatname(s int) string {
	if s >= 0 && s < len(postgresStatenames) {
		if postgresStatenames[s] != "" {
			return postgresStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func postgresErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !postgresErrorVerbose {
		return "syntax error"
	}

	for _, e := range postgresErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + postgresTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(postgresPact[state])
	for tok := TOKSTART; tok-1 < len(postgresToknames); tok++ {
		if n := base + tok; n >= 0 && n < postgresLast && int(postgresChk[int(postgresAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if postgresDef[state] == -2 {
		i := 0
		for postgresExca[i] != -1 || int(postgresExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; postgresExca[i] >= 0; i += 2 {
			tok := int(postgresExca[i])
			if tok < TOKSTART || postgresExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if postgresExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += postgresTokname(tok)
	}
	return res
}

func postgreslex1(lex postgresLexer, lval *postgresSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(postgresTok1[0])
		goto out
	}
	if char < len(postgresTok1) {
		token = int(postgresTok1[char])
		goto out
	}
	if char >= postgresPrivate {
		if char < postgresPrivate+len(postgresTok2) {
			token = int(postgresTok2[char-postgresPrivate])
			goto out
		}
	}
	for i := 0; i < len(postgresTok3); i += 2 {
		token = int(postgresTok3[i+0])
		if token == char {
			token = int(postgresTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(postgresTok2[1]) /* unknown char */
	}
	if postgresDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", postgresTokname(token), uint(char))
	}
	return char, token
}

func postgresParse(postgreslex postgresLexer) int {
	return postgresNewParser().Parse(postgreslex)
}

func (postgresrcvr *postgresParserImpl) Parse(postgreslex postgresLexer) int {
	var postgresn int
	var postgresVAL postgresSymType
	var postgresDollar []postgresSymType
	_ = postgresDollar // silence set and not used
	postgresS := postgresrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	postgresstate := 0
	postgresrcvr.char = -1
	postgrestoken := -1 // postgresrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		postgresstate = -1
		postgresrcvr.char = -1
		postgrestoken = -1
	}()
	postgresp := -1
	goto postgresstack

ret0:
	return 0

ret1:
	return 1

postgresstack:
	/* put a state and value onto the stack */
	if postgresDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", postgresTokname(postgrestoken), postgresStatname(postgresstate))
	}

	postgresp++
	if postgresp >= len(postgresS) {
		nyys := make([]postgresSymType, len(postgresS)*2)
		copy(nyys, postgresS)
		postgresS = nyys
	}
	postgresS[postgresp] = postgresVAL
	postgresS[postgresp].yys = postgresstate

postgresnewstate:
	postgresn = int(postgresPact[postgresstate])
	if postgresn <= postgresFlag {
		goto postgresdefault /* simple state */
	}
	if postgresrcvr.char < 0 {
		postgresrcvr.char, postgrestoken = postgreslex1(postgreslex, &postgresrcvr.lval)
	}
	postgresn += postgrestoken
	if postgresn < 0 || postgresn >= postgresLast {
		goto postgresdefault
	}
	postgresn = int(postgresAct[postgresn])
	if int(postgresChk[postgresn]) == postgrestoken { /* valid shift */
		postgresrcvr.char = -1
		postgrestoken = -1
		postgresVAL = postgresrcvr.lval
		postgresstate = postgresn
		if Errflag > 0 {
			Errflag--
		}
		goto postgresstack
	}

postgresdefault:
	/* default state action */
	postgresn = int(postgresDef[postgresstate])
	if postgresn == -2 {
		if postgresrcvr.char < 0 {
			postgresrcvr.char, postgrestoken = postgreslex1(postgreslex, &postgresrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if postgresExca[xi+0] == -1 && int(postgresExca[xi+1]) == postgresstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			postgresn = int(postgresExca[xi+0])
			if postgresn < 0 || postgresn == postgrestoken {
				break
			}
		}
		postgresn = int(postgresExca[xi+1])
		if postgresn < 0 {
			goto ret0
		}
	}
	if postgresn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			postgreslex.Error(postgresErrorMessage(postgresstate, postgrestoken))
			Nerrs++
			if postgresDebug >= 1 {
				__yyfmt__.Printf("%s", postgresStatname(postgresstate))
				__yyfmt__.Printf(" saw %s\n", postgresTokname(postgrestoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for postgresp >= 0 {
				postgresn = int(postgresPact[postgresS[postgresp].yys]) + postgresErrCode
				if postgresn >= 0 && postgresn < postgresLast {
					postgresstate = int(postgresAct[postgresn]) /* simulate a shift of "error" */
					if int(postgresChk[postgresstate]) == postgresErrCode {
						goto postgresstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if postgresDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", postgresS[postgresp].yys)
				}
				postgresp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if postgresDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", postgresTokname(postgrestoken))
			}
			if postgrestoken == postgresEofCode {
				goto ret1
			}
			postgresrcvr.char = -1
			postgrestoken = -1
			goto postgresnewstate /* try again in the same state */
		}
	}

	/* reduction by production postgresn */
	if postgresDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", postgresn, postgresStatname(postgresstate))
	}

	postgresnt := postgresn
	postgrespt := postgresp
	_ = postgrespt // guard against "declared and not used"

	postgresp -= int(postgresR2[postgresn])
	// postgresp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if postgresp+1 >= len(postgresS) {
		nyys := make([]postgresSymType, len(postgresS)*2)
		copy(nyys, postgresS)
		postgresS = nyys
	}
	postgresVAL = postgresS[postgresp+1]

	/* consult goto table to find next state */
	postgresn = int(postgresR1[postgresn])
	postgresg := int(postgresPgo[postgresn])
	postgresj := postgresg + postgresS[postgresp].yys + 1

	if postgresj >= postgresLast {
		postgresstate = int(postgresAct[postgresg])
	} else {
		postgresstate = int(postgresAct[postgresj])
		if int(postgresChk[postgresstate]) != -postgresn {
			postgresstate = int(postgresAct[postgresg])
		}
	}
	// dummy call; replaced with literal code
	switch postgresnt {

	case 5:
		postgresDollar = postgresS[postgrespt-9 : postgrespt+1]
//line ddl.y:56
		{
			lex := postgreslex.(*lexer)
			tb := newTableBuilder(postgresDollar[5].qname.schema, postgresDollar[5].qname.name)
			for _, elem := range postgresDollar[7].elements {
				if elem.column != nil {
					tb.addColumn(elem.column)
				}
				if elem.constraint != nil {
					tb.applyConstraint(elem.constraint)
				}
			}
			lex.addTable(tb)
		}
	case 8:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:77
		{
			postgresVAL.str = ""
		}
	case 9:
		postgresDollar = postgresS[postgrespt-4 : postgrespt+1]
//line ddl.y:78
		{
			postgresVAL.str = ""
		}
	case 10:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:79
		{
			postgresVAL.str = postgresDollar[2].str
		}
	case 17:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:95
		{
			postgresVAL.boolVal = false
		}
	case 18:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:96
		{
			postgresVAL.boolVal = true
		}
	case 19:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:100
		{
			postgresVAL.elements = []tableElement{postgresDollar[1].element}
		}
	case 20:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:101
		{
			postgresVAL.elements = append(postgresDollar[1].elements, postgresDollar[3].element)
		}
	case 21:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:102
		{
			postgresVAL.elements = postgresDollar[1].elements
		}
	case 22:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:106
		{
			postgresVAL.element = tableElement{column: postgresDollar[1].column}
		}
	case 23:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:107
		{
			postgresVAL.element = tableElement{constraint: postgresDollar[1].constraint}
		}
	case 24:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:111
		{
			col := &columnDef{name: postgresDollar[1].str, dbType: postgresDollar[2].str}
			applyColumnConstraints(col, postgresDollar[3].colcons)
			postgresVAL.column = col
		}
	case 25:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:119
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 26:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:120
		{
			postgresVAL.str = postgresDollar[1].str + " " + postgresDollar[2].str
		}
	case 27:
		postgresDollar = postgresS[postgrespt-4 : postgrespt+1]
//line ddl.y:121
		{
			postgresVAL.str = postgresDollar[1].str + "(" + postgresDollar[3].str + ")"
		}
	case 28:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:122
		{
			postgresVAL.str = postgresDollar[1].str + "[]"
		}
	case 29:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:126
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 30:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:127
		{
			postgresVAL.str = postgresDollar[1].str + "," + postgresDollar[3].str
		}
	case 31:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:131
		{
			postgresVAL.colcons = nil
		}
	case 32:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:132
		{
			postgresVAL.colcons = append(postgresDollar[1].colcons, postgresDollar[2].col)
		}
	case 33:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:136
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintNotNull}
		}
	case 34:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:137
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintNull}
		}
	case 35:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:138
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintPrimaryKey}
		}
	case 36:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:139
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintUnique}
		}
	case 37:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:140
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintDefault, value: postgresDollar[2].str}
		}
	case 38:
		postgresDollar = postgresS[postgrespt-5 : postgrespt+1]
//line ddl.y:141
		{
			ref := postgresDollar[2].fkTarget
			_ = postgresDollar[3].str
			ref.actions = postgresDollar[4].fkActions
			postgresVAL.col = columnConstraint{kind: columnConstraintForeignKey, fk: &ref}
		}
	case 39:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:147
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintNoop}
		}
	case 40:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:148
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintNoop}
		}
	case 41:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:149
		{
			postgresVAL.col = columnConstraint{kind: columnConstraintNoop}
		}
	case 47:
		postgresDollar = postgresS[postgrespt-6 : postgrespt+1]
//line ddl.y:167
		{
			postgresVAL.constraint = &constraintDef{kind: constraintPrimaryKey, name: postgresDollar[1].str, columns: postgresDollar[5].strList}
		}
	case 48:
		postgresDollar = postgresS[postgrespt-6 : postgrespt+1]
//line ddl.y:170
		{
			name := postgresDollar[1].str
			if name == "" {
				name = postgresDollar[3].str
			}
			postgresVAL.constraint = &constraintDef{kind: constraintUnique, name: name, columns: postgresDollar[5].strList}
		}
	case 49:
		postgresDollar = postgresS[postgrespt-11 : postgrespt+1]
//line ddl.y:177
		{
			postgresVAL.constraint = &constraintDef{
				kind:    constraintForeignKey,
				name:    postgresDollar[1].str,
				columns: postgresDollar[5].strList,
				fk: fkTarget{
					table:   postgresDollar[8].fkTarget.table,
					columns: postgresDollar[8].fkTarget.columns,
					actions: postgresDollar[10].fkActions,
				},
			}
		}
	case 50:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:189
		{
			postgresVAL.constraint = nil
		}
	case 53:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:198
		{
			postgresVAL.str = ""
		}
	case 54:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:199
		{
			postgresVAL.str = postgresDollar[2].str
		}
	case 55:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:203
		{
			postgresVAL.str = ""
		}
	case 56:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:204
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 57:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:208
		{
			_ = postgresDollar[1].boolVal
			postgresVAL.fkTarget = fkTarget{table: postgresDollar[2].qname, columns: postgresDollar[3].strList}
		}
	case 58:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:215
		{
			postgresVAL.str = ""
		}
	case 59:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:216
		{
			postgresVAL.str = postgresDollar[2].str
		}
	case 60:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:220
		{
			postgresVAL.strList = nil
		}
	case 61:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:221
		{
			postgresVAL.strList = postgresDollar[2].strList
		}
	case 62:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:225
		{
			postgresVAL.fkActions = fkActions{}
		}
	case 63:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:226
		{
			postgresVAL.fkActions = postgresDollar[1].fkActions
			if postgresDollar[2].fkActions.onDelete != "" {
				postgresVAL.fkActions.onDelete = postgresDollar[2].fkActions.onDelete
			}
			if postgresDollar[2].fkActions.onUpdate != "" {
				postgresVAL.fkActions.onUpdate = postgresDollar[2].fkActions.onUpdate
			}
		}
	case 64:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:238
		{
			postgresVAL.fkActions = fkActions{onDelete: postgresDollar[3].str}
		}
	case 65:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:239
		{
			postgresVAL.fkActions = fkActions{onUpdate: postgresDollar[3].str}
		}
	case 66:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:243
		{
			postgresVAL.str = "CASCADE"
		}
	case 67:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:244
		{
			postgresVAL.str = "RESTRICT"
		}
	case 68:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:245
		{
			postgresVAL.str = "NO ACTION"
		}
	case 69:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:246
		{
			postgresVAL.str = "SET NULL"
		}
	case 70:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:247
		{
			postgresVAL.str = "SET DEFAULT"
		}
	case 76:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:259
		{
			postgresVAL.strList = []string{postgresDollar[1].str}
		}
	case 77:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:260
		{
			postgresVAL.strList = append(postgresDollar[1].strList, postgresDollar[3].str)
		}
	case 78:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:264
		{
			postgresVAL.qname = qualifiedName{name: postgresDollar[1].str}
		}
	case 79:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:265
		{
			postgresVAL.qname = qualifiedName{schema: postgresDollar[1].str, name: postgresDollar[3].str}
		}
	case 80:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:269
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 81:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:270
		{
			postgresVAL.str = postgresDollar[1].str + "." + postgresDollar[3].str
		}
	case 82:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:274
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 83:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:275
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 84:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:276
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 85:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:277
		{
			postgresVAL.str = "(" + postgresDollar[2].str + ")"
		}
	case 86:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:278
		{
			postgresVAL.str = postgresDollar[1].str + "::" + postgresDollar[3].str
		}
	case 87:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:279
		{
			postgresVAL.str = postgresDollar[1].str + " + " + postgresDollar[3].str
		}
	case 88:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:280
		{
			postgresVAL.str = postgresDollar[1].str + " - " + postgresDollar[3].str
		}
	case 89:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:281
		{
			postgresVAL.str = postgresDollar[1].str + " * " + postgresDollar[3].str
		}
	case 90:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:282
		{
			postgresVAL.str = postgresDollar[1].str + " / " + postgresDollar[3].str
		}
	case 91:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:283
		{
			postgresVAL.str = "-" + postgresDollar[2].str
		}
	case 92:
		postgresDollar = postgresS[postgrespt-2 : postgrespt+1]
//line ddl.y:284
		{
			postgresVAL.str = "+" + postgresDollar[2].str
		}
	case 93:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:288
		{
			postgresVAL.str = quoteLiteral(postgresDollar[1].str)
		}
	case 94:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:289
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 95:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:290
		{
			postgresVAL.str = "TRUE"
		}
	case 96:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:291
		{
			postgresVAL.str = "FALSE"
		}
	case 97:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:292
		{
			postgresVAL.str = "NULL"
		}
	case 98:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:293
		{
			postgresVAL.str = "CURRENT_TIMESTAMP"
		}
	case 99:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:294
		{
			postgresVAL.str = "CURRENT_DATE"
		}
	case 100:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:295
		{
			postgresVAL.str = "CURRENT_TIME"
		}
	case 101:
		postgresDollar = postgresS[postgrespt-4 : postgrespt+1]
//line ddl.y:299
		{
			if postgresDollar[3].str == "" {
				postgresVAL.str = postgresDollar[1].str + "()"
			} else {
				postgresVAL.str = postgresDollar[1].str + "(" + postgresDollar[3].str + ")"
			}
		}
	case 102:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:309
		{
			postgresVAL.str = ""
		}
	case 103:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:310
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 104:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:314
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 105:
		postgresDollar = postgresS[postgrespt-3 : postgrespt+1]
//line ddl.y:315
		{
			postgresVAL.str = postgresDollar[1].str + ", " + postgresDollar[3].str
		}
	case 106:
		postgresDollar = postgresS[postgrespt-13 : postgrespt+1]
//line ddl.y:319
		{
			lex := postgreslex.(*lexer)
			lex.addIndex(indexDef{
				schema:  postgresDollar[7].qname.schema,
				table:   postgresDollar[7].qname.name,
				name:    postgresDollar[4].str,
				columns: postgresDollar[10].strList,
				unique:  postgresDollar[2].boolVal,
			})
		}
	case 107:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:332
		{
			postgresVAL.boolVal = false
		}
	case 108:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:333
		{
			postgresVAL.boolVal = true
		}
	case 115:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:352
		{
			postgresVAL.str = postgresDollar[1].str
		}
	case 116:
		postgresDollar = postgresS[postgrespt-0 : postgrespt+1]
//line ddl.y:356
		{
			postgresVAL.boolVal = false
		}
	case 117:
		postgresDollar = postgresS[postgrespt-1 : postgrespt+1]
//line ddl.y:357
		{
			postgresVAL.boolVal = true
		}
	}
	goto postgresstack /* stack new state and value */
}
